CREATE TABLE VEÍCULO
(
    ID INT PRIMARY KEY CHECK(ID>=0 AND ID<=1000),
    CONSUMO INT,
    COR TEXT,
    ANO DATE,
    PESO INT,
    PREÇO INT,
    TRAÇÃO TEXT,
    NÚMERO_DE_ASSENTOS INT,
    ESTADO TEXT,
    SÉRIE INT,
    ID_VENDEDOR INT,
    FOREIGN KEY SÉRIE REFERENCES MOTOR(NÚMERO_DE_SÉRIE),
    FOREIGN KEY ID_VENDEDOR REFERENCES VENDEDOR(ID),
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE TABLE MOTOR
(
    NÚMERO_DE_SÉRIE INT PRIMARY KEY,
    NOME TEXT,
    CILINDRADA INT,
    NÚMERO_DE_CILINDROS INT,
    NÚMERO_DE_VÁLVULAS INT,
    ASPIRAÇÃO TEXT,
    BINÁRIO INT,
    POTÊNCIA INT,
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE TABLE COMBUSTÍVEL 
(
    ID INT PRIMARY KEY,
    TIPO TEXT
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE TABLE FUNCIONA_A
(
    ID_VEÍCULO INT,
    ID_COMBUSTÍVEL INT,
    PRIMARY KEY (ID_VEÍCULO,ID_COMBUSTÍVEL),
    FOREIGN KEY ID_VEÍCULO REFERENCES VEÍCULO(ID),
    FOREIGN KEY ID_COMBUSTÍVEL REFERENCES COMBUSTÍVEL(ID),
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE TABLE UTILIZADOR
(
    ID INT PRIMARY KEY,
    EMAIL TEXT,
    HASH_PALAVRA_PASSE INT,
    USERNAME TEXT,
    PAÍS TEXT,
    MORADA TEXT,
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE TABLE CLIENTE
(
    ID INT PRIMARY KEY,
    PREFERÊNCIAS TEXT,
    FOREIGN KEY ID REFERENCES UTILIZADOR(ID),
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE TABLE VENDEDOR
(
    ID INT PRIMARY KEY,
    HISTÓRICO TEXT,
    MARCA_ASSOCIADA TEXT,
    FOREIGN KEY ID REFERENCES UTILIZADOR(ID),
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

